MyFinance/Controllers/ContaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyFinance.Models;

namespace MyFinance.Controllers
{
    public class ContaController : Controller
    {
        IHttpContextAccessor HttpContextAccessor;

        public ContaController(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            ContaModel objConta = new ContaModel(HttpContextAccessor);
            ViewBag.ListaConta = objConta.ListaConta();
            return View();
        }

        [HttpPost]
        public IActionResult CriarConta(ContaModel formulario)
        {
            if (ModelState.IsValid)
            {
                formulario.HttpContextAccessor = HttpContextAccessor;
                formulario.Insert();
                return RedirectToAction("Index");
            }   

            return View();
        }

        [HttpGet]
        public IActionResult CriarConta()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ExcluirConta(int id)
        {
            ContaModel objConta = new ContaModel(HttpContextAccessor);
            objConta.Excluir(id);
            return RedirectToAction("Index");
        }

    }
}

MyFinance/Views/Conta/CriarConta.cshtml
@model ContaModel

@{
    ViewData["Title"] = "CriarConta";
}

<h2>Criar Conta</h2> <br />

<form asp-controller="Conta" asp-action="CriarConta">
    <div class="form-group">
        <label for="name">Nome:</label>
        <input type="text" class="form-control" asp-for="NomeConta" placeholder="Entre com sua conta">
        <span asp-validation-for="NomeConta"></span>
    </div>
    <div class="form-group">
        <label for="name">Saldo:</label>
        <input type="number" class="form-control" asp-for="Saldo" placeholder="Informe seu Saldo">
        <span asp-validation-for="Saldo"></span>
    </div>

    <button type="submit" class="btn btn-success">Registrar</button>
</form>

MyFinance/Views/Conta/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Minhas Contas</h2> <br />


<button type="button" class="btn btn-primary" onclick="CriarConta()">Criar Conta</button> <br /><br />


<input type="file" class="custom-file" value="Importar Plano Conta" />


<table class="table table-bordered">

    <thead>
        <tr>
            <th>#</th>
            <th>ID</th>
            <th>Nome</th>
            <th>Saldo</th>
        </tr>
    </thead>


    @{ 


        foreach (var item in (List<ContaModel>)ViewBag.ListaConta)
        {

            <tbody>
                <tr>
                    <td><button type="button" class="btn btn-danger" onclick="Excluir(@item.Id.ToString())">Excluir</button></td>
                    <td>@item.Id.ToString()</td>
                    <td>@item.NomeConta.ToString()</td>
                    <td>R$ @item.Saldo.ToString()</td>
                </tr>
            </tbody>
            }
       
    }

</table>


<script>

    function CriarConta() {

        window.location.href = "../Conta/CriarConta"
    }

    function Excluir(id_conta) {

        window.location.href = "../Conta/ExcluirConta/" + id_conta;

    }
</script>