MyFinance/Controllers/TransacaoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyFinance.Models;
using System;
using System.Collections.Generic;

namespace MyFinance.Controllers
{
    public class TransacaoController : Controller
    {
        IHttpContextAccessor HttpContextAccessor;

        public TransacaoController(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            TransacaoModel objTransacao = new TransacaoModel(HttpContextAccessor);
            ViewBag.ListaTransacao = objTransacao.ListaTransacao();
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(TransacaoModel formulario)
        {
            if (ModelState.IsValid)
            {
                formulario.HttpContextAccessor = HttpContextAccessor;
                formulario.Insert();
                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult Registrar(int? id)
        {
            if (id != null)
            {
                TransacaoModel objTransacao = new TransacaoModel(HttpContextAccessor);
                ViewBag.Registro = objTransacao.CarregarRegistro(id);
            }

            ViewBag.ListaContas = new ContaModel(HttpContextAccessor).ListaConta();
            ViewBag.ListaPlanoContas = new PlanoContasModel(HttpContextAccessor).ListaPlano();

            return View();
        }

        [HttpGet]
        public IActionResult ExcluirTransacao(int id)
        {
            TransacaoModel objTransacao = new TransacaoModel(HttpContextAccessor);
            ViewBag.Registro = objTransacao.CarregarRegistro(id);

            return View();
        }

        [HttpGet]
        public IActionResult Excluir(int id)
        {
            TransacaoModel objTransacao = new TransacaoModel(HttpContextAccessor);
            objTransacao.Excluir(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [HttpPost]
        public IActionResult Extrato(TransacaoModel formulario) 
        {
            formulario.HttpContextAccessor = HttpContextAccessor;
            ViewBag.ListaTransacao = formulario.ListarTransacao();
            ViewBag.ListaContas = new ContaModel(HttpContextAccessor).ListaConta();
            return View();
        }

        public IActionResult DashBoard()
        {
            Dashboard objdashboard = new Dashboard();

            List<Dashboard> lista = new Dashboard(HttpContextAccessor).dashboardsPie();

            string valores = "";
            string labels = "";
            string cores = "";

            var random = new Random();
            
            for (int i = 0; i < lista.Count; i++)
            {
                valores += lista[i].Total.ToString() + ",";
                labels += "'" + lista[i].PlanoConta.ToString() + "',";
                cores += "'" + string.Format("#{0:x6}", random.Next(0x1000000) + "',");
            }

            ViewBag.cores = cores;
            ViewBag.Valores = valores;
            ViewBag.labels = labels;

            return View();
        }
    }
}

MyFinance/Views/Transacao/DashBoard.cshtml
@{
    ViewData["Title"] = "DashBoard";
}

<h1>DashBoard</h1>
<br />
<br />

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>

<div id="canvas-holder" style="width:60%">
    <canvas id="chart-area"></canvas>
</div>
<script>
    var randomScalingFactor = function () {
        return Math.round(Math.random() * 100);
    };

    var config = {
        type: 'pie',
        data: {
            datasets: [{
                data: [

                    @Html.Raw(ViewBag.Valores)
                ],
                backgroundColor: [

                   @Html.Raw(ViewBag.cores)
                ],

                label: 'Dataset 1'
            }],
            labels: [

                @Html.Raw(ViewBag.labels)
            ]
        },
        options: {
            responsive: true
        }
    };

    window.onload = function () {
        var ctx = document.getElementById('chart-area').getContext('2d');
        window.myPie = new Chart(ctx, config);
    };


</script>

MyFinance/Views/Transacao/Extrato.cshtml
@model TransacaoModel

<h1>Meu Extrato</h1>

<div class="container">
    <form asp-controller="Transacao" asp-action="Extrato">
        <div class="form-group">
            <label>Data Transação (Inicio): </label>
            <input type="date" asp-for="Data" class="form-control" />
        </div>
        <div class="form-group">
            <label>Data Transação (Final): </label>
            <input type="date" asp-for="Data" class="form-control" />
        </div>
        <div class="form-group">
            <label>Tipo Transação: </label>
            <div class="radio"><label><input type="radio" asp-for="Tipo" value="A" checked />Receitas e Despesas</label></div>
            <div class="radio"><label><input type="radio" asp-for="Tipo" value="R" />Receita</label></div>
            <div class="radio"><label><input type="radio" asp-for="Tipo" value="D" />Despesa</label></div>
        </div>

        <div class="form-group">
            <label>Conta: </label>
            <select asp-for="Conta_id" class="form-control">
                @{
                    foreach (var item in (List<ContaModel>)ViewBag.ListaContas)
                    {
                        <option value="@item.Id.ToString()">@item.NomeConta.ToString()</option>
                    }
                }
            </select>
        </div>
        <button type="submit" class="btn btn-success">Pesquisar</button>
    </form>
</div>
<br />

<table class="table table-bordered">


    <thead>
        <tr>
            <th>ID</th>
            <th>Data</th>
            <th>Tipo</th>
            <th>Valor</th>
            <th>Historico</th>
            <th>Conta</th>
            <th>Plano de Contas</th>
            <th>Ação</th>
        </tr>
    </thead>

    @{
        var TotalReceitas = 0.0;
        var TotalDespesas = 0.0;
        var vsaldo = 0.0;

        foreach (var item in (List<TransacaoModel>)ViewBag.ListaTransacao)
        {
            <tbody>
                <tr>
                    <td>@item.Id.ToString()</td>
                    <td>@item.Data.ToString()</td>
                    <td>@item.Tipo.ToString().Replace("R", "Receita").Replace("D", "Despesa")</td>
                    <td>R$ @item.Valor.ToString()</td>
                    <td>@item.Descricao</td>
                    <td>@item.NomeConta.ToString()</td>
                    <td>@item.DescricaoPlanoConta.ToString()</td>
                    <td><button type="button" class="btn btn-primary" onclick="Editar(@item.Id.ToString())">Editar</button></td>
                </tr>

                @{
                    if (item.Tipo == "D")
                    {
                        TotalDespesas += double.Parse(item.Valor.ToString());
                    }

                    TotalReceitas += double.Parse(item.Valor.ToString());
                }
            </tbody>
        }

        vsaldo = TotalReceitas - TotalDespesas;

    }

</table>
<h4><strong>Saldo:</strong> R$@vsaldo</h4>

<script>

    function Editar(id) {

        window.location.href = "../Transacao/Registrar/" + id;
    }

</script>

MyFinance/Views/Transacao/Index.cshtml
<h2>Minhas Transações</h2> <br />

<button type="button" class="btn btn-primary" onclick="RegistrarTransacao()">Registrar Transação</button> <br /><br />

<div class="table-responsive-lg">

    <table class="table table-bordered">


        <thead>
            <tr>
                <th>ID</th>
                <th>Data</th>
                <th>Tipo</th>
                <th>Valor</th>
                <th>Historico</th>
                <th>Conta</th>
                <th>Plano de Contas</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>

        @{
            foreach (var item in (List<TransacaoModel>)ViewBag.ListaTransacao)
            {
                <tbody>
                    <tr>
                        <td>@item.Id.ToString()</td>
                        <td>@item.Data.ToString()</td>
                        <td>@item.Tipo.ToString().Replace("R", "Receita").Replace("D", "Despesa")</td>
                        <td>R$ @item.Valor.ToString()</td>
                        <td>@item.Descricao</td>
                        <td>@item.NomeConta.ToString()</td>
                        <td>@item.DescricaoPlanoConta.ToString()</td>
                        <td>
                            <button type="button" class="btn btn-primary" onclick="Editar(@item.Id.ToString())">Editar</button>
                            <button type="button" class="btn btn-danger" onclick="Excluir(@item.Id.ToString())">Excluir</button>

                        </td>
                    </tr>
                </tbody>
            }
        }

    </table>



    @* MODAL EXCLUIR *@

    <div class="modal fade" id="ExcluirTransacao" tabindex="-1" role="dialog" aria-labelledby="ExcluirTransacao" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">

            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="TituloModalCentralizado">Excluir Esta Transação?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-content">
                    <button type="button" class="btn btn-danger" onclick="Excluir(@Html.ViewBag.Registro)">Sim! Quero Excluir</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>

</div>


<script>

    function RegistrarTransacao() {

        window.location.href = "../Transacao/Registrar";
    }

    function Excluir(id) {

        window.location.href = "../Transacao/Excluir/" + id;
    }
    function Editar(id) {

        window.location.href = "../Transacao/Registrar/" + id;
    }
</script>

MyFinance/Views/Transacao/Registrar.cshtml
@model TransacaoModel

@{
    ViewData["Title"] = "CriarPlanoConta";
}

<h2>Registrar Transação</h2> <br />

@{
    var vData = "";
    var vTipo = "";
    var vValor = 0.0;
    var vDescricao = "";
    var vId = 0;
    var vContaId = 0;
    var vPlaContasId = 0;

    try
    {
        vId = int.Parse(@ViewBag.Registro.Id.ToString());
        vData = DateTime.Parse(@ViewBag.Registro.Data.ToString()).ToString("yyyy-MM-dd");
        vContaId = int.Parse(@ViewBag.Registro.Conta_id.ToString());
        vPlaContasId = int.Parse(@ViewBag.Registro.Plano_Contas_Id.ToString());
        vDescricao = @ViewBag.Registro.Descricao.ToString();
        vTipo = @ViewBag.Registro.tipo.ToString();
        vValor = double.Parse(@ViewBag.Registro.valor.ToString());
    }

    catch { }

}

<div class="container">
    <form asp-controller="Transacao" asp-action="Registrar">
        <input type="hidden" asp-for="Id" value="@vId" />

        <div class="form-group">
            <label>Data:</label>
            <input type="date" class="form-control" asp-for="Data" value="@vData">
            <span asp-validation-for="Data" class="text-danger"></span>
        </div>


        <div class="form-group">
            <label for="name">Tipo:</label>
            @{
                if (vTipo == "R")
                {
                    <div class="radio"><label><input type="radio" class="form-control" asp-for="Tipo" value="R" checked>Receita</label></div>
                    <div class="radio"><label><input type="radio" class="form-control" asp-for="Tipo" value="D" unchecked>Despesa</label></div>
                }
                else
                {
                    <div class="radio"><label><input type="radio" class="form-control" asp-for="Tipo" value="R" unchecked>Receita</label></div>
                    <div class="radio"><label><input type="radio" class="form-control" asp-for="Tipo" value="D" checked>Despesa</label></div>
                }
            }

        </div>


        <div class="form-group">
            <label>Valor:</label>
            <input type="number" class="form-control" asp-for="Valor" value="@vValor">
            <span asp-validation-for="Valor"></span>
        </div>

        <div class="form-group">
            <label>Histórico:</label>
            @Html.TextArea("Descricao", vDescricao, new { @class = "form-control" })
            <span asp-validation-for="Descricao"></span>
        </div>

        <div class="form-group">
            <label>Conta: </label>
            <select asp-for="Conta_id" class="form-control">
                @{
                    foreach (var item in (List<ContaModel>)ViewBag.ListaContas)
                    {
                        if (item.Id.ToString() == vContaId.ToString())
                        {
                            <option selected value="@item.Id.ToString()">@item.NomeConta.ToString()</option>
                        }
                        else
                        {
                            <option value="@item.Id.ToString()">@item.NomeConta.ToString()</option>
                        }

                    }
                }
            </select>
        </div>

        <div class="form-group">
            <label>Plano de Contas: </label>
            <select asp-for="Plano_Contas_Id" class="form-control">
                @{
                    foreach (var item in (List<PlanoContasModel>)ViewBag.ListaPlanoContas)
                    {
                        if (item.Id.ToString() == vPlaContasId.ToString())
                        {
                            <option selected value="@item.Id.ToString()">@item.Descricao.ToString()</option>
                        }
                        <option value="@item.Id.ToString()">@item.Descricao.ToString()</option>
                    }
                }
            </select>
        </div>


        <button type="submit" class="btn btn-success">Registrar</button>
    </form>
</div>